# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
 email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
 email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
 mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
 mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
 domain_name: example.com
 owner_email: <%= ENV["OWNER_EMAIL"] %>
 secret_key_base: 42302d002ac5bfd4cd5e904f9cfb95e422dae79a82ee750d4946c49f2e60ad44682b4f42ae41516886c0a506a4b74249382ac0cf2bee6adad07bf2ac77cd7198

test:
 secret_key_base: 6268fa296bb6920b4314696bbe9daf4d37161216db7ef72f4cee35e0d3567b55f341e0f270f960038b4b10f7ae276a00a1efb51c8f44a38ab7a857ff5e7b0551

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
 mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
 mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
 secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
